### ISSUE TITLE
iczc.cz blokuje obrázky zboží na czc.cz

### ISSUE THREAD

**Issue by rradeg** [qxstyles/turris-hole-czech-block-list#2]
Ahoj, kvůli čemu je blokovaná doména iczc.cz? Myslím, že by stálo za to upravit pravidlo tak, aby czc.cz byly vidět obrázky zboží. Díky

**Comment by qxstyles** [comment]
Dobrý den/ahoj. Záznam jsem odebral. Děkuji za podnět. V době, kdy jsem to tam dával to fungovalo (nebo jsem si toho nějak nevšiml). Podle mě v minulosti z toho zdroje iczc.cz dříve tapetovali to pozadí reklamou, proto jsem to tam takto přidal. Od té doby jsem byl na czc.cz párkrát/nebo jsem to měl ještě v cache a nevšiml jsem si toho.
