### ISSUE TITLE
+toplist.cz, +spir.hit.gemius.pl, +toplist.sk, 

### ISSUE THREAD

**Issue by jose-d** [qxstyles/turris-hole-czech-block-list#4]
ahoj, viz SUBJ

**Comment by MattXcz** [comment]
@qxstyles ... Pro rychlejší načítání stránek bych je odebral

**Comment by qxstyles** [comment]
a jen ty s *.hit.gemius.pl nebo *.imedia.cz nebo i položky z původního požadavku?

**Comment by MattXcz** [comment]
Odebrat:
```
*.hit.gemius.pl
*.imedia.cz
```
Přidat:
```
toplist.cz
toplist.sk
spir.hit.gemius.pl 
```
U spir.hit.gemius.pl zatím nevím jak se stránky budou chovat. Zatím můžeme přidat a uvidíme jestli se někdo ozve.

**Comment by qxstyles** [comment]
Je to tam, děkuji.
