### ISSUE TITLE
navrh na blokacie

### ISSUE THREAD

**Issue by rchovan** [qxstyles/turris-hole-czech-block-list#6]
Zdravim, skusali ste tuto stranku ?
https://pi-hole.net/pages-to-test-ad-blocking-performance/
Nechcete pridat este zobrazujuce sa reklamy ?

**Comment by qxstyles** [comment]
Dobrý den,

omlouvám se za pomalou reakci, nějak jsem na všechno tady zapomněl a nějak se to ve všech těch mailech ztratilo. 

Já tento seznam "udržuji" vedle těch známých, co jsou zveřejněné někde na Pihole (ať už web nebo forum). Sám osobně používám kombinaci několika blocklistů, a proto si myslím, že by bylo zbytečné a nesmyslné "můj seznam" doplňovat o něco, co už někde je, a je prakticky snazší přidat si ten zdroj do vlastního Piholu přímo od autora, který se o zdroj asi i stará víc.

V.D.

**Comment by MattXcz** [comment]
Nejlepší by bylo tento seznam udržovat pro ryze české reklamy...
